// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CodeCrafty.DapperDan.Data.CompiledModels
{
    public partial class DapperDanDbContextModel
    {
        private DapperDanDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("4d9c20ea-da25-4127-bf04-b92a9cd5ad8a"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var keiki = KeikiEntityType.Create(this);
            var keikiMemory = KeikiMemoryEntityType.Create(this);

            KeikiMemoryEntityType.CreateForeignKey1(keikiMemory, keiki);

            KeikiEntityType.CreateAnnotations(keiki);
            KeikiMemoryEntityType.CreateAnnotations(keikiMemory);

            AddAnnotation("ProductVersion", "10.0.5");
        }
    }
}
