// <auto-generated />
using CodeCrafty.DapperDan.Data;
using CodeCrafty.DapperDan.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DapperDanDbContext), typeof(DapperDanDbContextModel))]
